pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment { 
        Course = 'Jenkins'
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    stages {
        stage('terraform init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('terraform plan') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }               
            }
        }
        stage('terraform apply') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }                
            }
        }


    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()

        }
        success {
            echo 'I will run if pipeline sucess'
        }
        failure {
            echo 'I will run if pipeline failed'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}