pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    environment { 
        Course = 'Jenkins'
    }
    options {
        timeout(time: 10, unit: 'MINUTES') 
        disableConcurrentBuilds()
    }
    stages {
        stage('terraform init') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform init
                        """
                    }
                }
            }
        }
        stage('terraform plan') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform plan
                        """
                    }
                }               
            }
        }
        stage('terraform apply') {
            steps {
                script {
                    withAWS(region:'us-east-1',credentials:'aws') {
                        sh """
                            cd 10-sg
                            terraform apply -auto-approve
                        """
                    }
                }                
            }
        }
        stage('Parallel Triggers') {
            parallel {
                stage('Trigger Bastion') {
                    steps {
                        build job: '20-bastion',
                            wait: false,
                            propagate: false
                    }
                }
                stage('Trigger SG Rules') {
                    steps {
                        build job: '30-sg-rules',
                            wait: false,
                            propagate: false
                    }
                }
                stage('Trigger ECR') {
                    steps {
                        build job: '40-ecr',
                            wait: false,
                            propagate: false
                    }
                }
                stage('Trigger ACM') {
                    steps {
                        build job: '70-acm',
                            wait: true,
                            propagate: true
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        build job: '90-eks',
                            wait: false,
                            propagate: false
                    }
                }
            }
        }
        stage('Trigger Frontend ALB') {
            steps {
                build job: '80-frontend-alb',
                    wait: false,
                    propagate: false
            }
        }
    


    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            cleanWs()

        }
        success {
            echo 'I will run if pipeline sucess'
        }
        failure {
            echo 'I will run if pipeline failed'
        }
        aborted {
            echo 'pipeline is aborted'
        }
    }
}